spring.application.name=websocket

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.web=DEBUG
logging.level.com.fasterxml.jackson=DEBUG

# GitHub OAuth
spring.security.oauth2.client.registration.github.client-id=${GH_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GH_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

jwt.secret=${SECRET_KEY}
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

cookie.access.name=${COOKIE_ACCESS_NAME}
cookie.access.http-only=${COOKIE_ACCESS_HTTP_ONLY}
cookie.access.secure=${COOKIE_ACCESS_SECURE}
cookie.access.path=${COOKIE_ACCESS_PATH}
cookie.access.max-age=${COOKIE_ACCESS_MAX_AGE}

cookie.refresh.name=${COOKIE_REFRESH_NAME}
cookie.refresh.http-only=${COOKIE_REFRESH_HTTP_ONLY}
cookie.refresh.secure=${COOKIE_REFRESH_SECURE}
cookie.refresh.path=${COOKIE_REFRESH_PATH}
cookie.refresh.max-age=${COOKIE_REFRESH_MAX_AGE}
